apiVersion: v1
kind: Namespace
metadata:
  name: openfaas
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas-fn
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---