---
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: email-notify
  namespace: openfaas-fn
spec:
  name: email-notify
  image: {{ .Values.emailNotify.image }}
  labels:
    com.openfaas.scale.zero: "{{ .Values.scaleToZero.enable | toString }}"
    com.openfaas.scale.zero-duration: "{{ .Values.scaleToZero.duration }}"

