---
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: nodeinfo
  namespace: openfaas-fn
spec:
  name: nodeinfo
  image: "{{ .Values.nodeInfo.image }}"
  labels:
    com.openfaas.scale.zero: "{{ .Values.scaleToZero.enable | toString }}"
    com.openfaas.scale.zero-duration: "{{ .Values.scaleToZero.duration }}"
